### ISSUE TITLE
Wrong repository in Cargo.toml

### ISSUE THREAD

**Issue by FrTerstappen** [ethereumdegen/bevy_foliage_tool#1]
Hello, 

the repository specified in the `Cargo.toml` file seems to be wrong. It currently looks like the following:

```
repository = "https://github.com/ethereumdegen/bevy_regions"
```

This points to one of your other projects and should be adjusted.

**Comment by ethereumdegen** [comment]
oh! thanks . That is the project i forked off from since it had some similar elements. Fixed
